name: Build python package

on:
  workflow_call:
    outputs:
      package-name:
        description: 'Name of the package'
        value: ${{ jobs.build.outputs.package-name }}

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest

    outputs:
      package-name: ${{ steps.package-name.outputs.name }}
      package-version: ${{ steps.package-name.outputs.version }}
      git-status: ${{ steps.git-status.outputs.status }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all tags to get correct version on build

      - name: Setup python environment
        uses: ./.github/setup

      - name: Build package
        run: uv build --no-sources

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package
          path: dist/

      - name: Check git status
        id: git-status
        run: echo "status=$(git status --porcelain)" >> $GITHUB_OUTPUT

      - name: Get package name and version
        id: package-name
        run: >-
          ls dist/*.whl |
          sed 's/^.*\/\([^-]*\)-\([^-]*\)-.*$/name=\1\nversion=\2/;1q'
          >> $GITHUB_OUTPUT
