name: Publish python package

on:
  workflow_call:
    inputs:
      package-name:
        description: 'Name of the package to publish'
        required: true
        type: string
      pypi:
        description: 'Set to "pypi" or "test.pypi" (default).'
        default: 'test.pypi'
        required: false
        type: string

jobs:
  publish:
    name: Publish package to ${{ inputs.pypi }}
    runs-on: ubuntu-latest

    environment:
      name: publish-${{ inputs.pypi }}
      url: https://${{ inputs.pypi }}.org/p/${{ inputs.package-name }}
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Publish package
        uses: glenn20/python-ci/publish@main
        with:
          pypi: ${{ inputs.pypi }}
