name: Publish and Release

on:
  push:
    tags: ["v*"]  # Publish on tags matching "v*", eg. "v1.0.0"
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/_ci_tests.yaml
    with:
      os: '["ubuntu-latest", "windows-latest", "macos-latest"]'
      python-version: '["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]'

  publish-pypi:
    name: Publish to pypi
    uses: ./.github/workflows/_publish.yaml
    needs: tests
    with:
      package-name: ${{ needs.tests.outputs.package-name }}
      pypi: test.pypi
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

  github-release:
    name: Create GitHub release
    uses: ./.github/workflows/_release.yaml
    needs: publish-pypi
    permissions:
      contents: write  # IMPORTANT: mandatory for trusted publishing
      id-token: write  # IMPORTANT: mandatory for trusted publishing
