name: Publish and Release

on:
  push:
    tags: ["v*"]  # Publish on tags matching "v*", eg. "v1.0.0"
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    uses: glenn20/python-ci/.github/workflows/_ci_tests.yaml@main
    with:
      os: '["ubuntu-latest", "windows-latest", "macos-latest"]'
      python-version: '["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]'

  publish-test:
    name: Publish to test.pypi
    runs-on: ubuntu-latest
    steps:
      - uses: glenn20/python-ci/publish@main
        with: { pypi: test.pypi }
    environment:
      name: publish-test.pypi
      url: https://test.pypi.org/p/glenn20-python-ci
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing!

  publish-pypi:
    name: Publish to pypi
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: glenn20/python-ci/publish@main
        with: { pypi: pypi }
    environment:
      name: publish-pypi
      url: https://pypi.org/p/glenn20-python-ci
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing!

  github-release:
    name: Create GitHub release
    uses: glenn20/python-ci/.github/workflows/_release.yaml@main
    needs: publish-test
    permissions:
      contents: write  # IMPORTANT: mandatory for github release
      id-token: write  # IMPORTANT: mandatory for github release
