name: Test and Build

on:
  push:
    branches: [main, dev]
  workflow_dispatch:
  workflow_call:
    outputs:
      package-name:
        description: 'Name of the package'
        value: ${{ jobs.ci.outputs.package-name }}

jobs:
  ci:
    name: Test and Build
    uses: ./.github/workflows/_test_ci.yaml
    with:
      os: '["ubuntu-latest", "windows-latest"]'
      python-version: '["3.8", "3.12"]'
