name: Test and Build

on:
  push:
    branches: [main, dev]
  workflow_dispatch:
  workflow_call:
    outputs:
      package-name:
        description: 'Name of the package'
        value: ${{ jobs.build.outputs.package-name }}

jobs:
  check:
    name: Code checks
    uses: ./.github/workflows/_check.yaml

  test:
    name: Tests
    uses: ./.github/workflows/_test.yaml
    with:
      os: '["ubuntu-latest"]'
      python-version: '["3.8", "3.12"]'

  build:
    name: Build package
    # if: github.event_name == 'push' && github.ref_name == 'main'
    uses: glenn20/python-ci/.github/workflows/_build.yaml@main

  publish-test:
    name: Publish to test.pypi
    uses: ./.github/workflows/_publish.yaml
    needs: build
    with:
      package-name: ${{ needs.build.outputs.package-name }}
      pypi: test.pypi
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
