name: Test and Build

on:
  push:
    branches: [main, dev]
  workflow_dispatch:
  workflow_call:

jobs:
  ci-tests:
    name: CI tests
    uses: ./.github/workflows/_ci_tests.yaml
    with:
      os: '["ubuntu-latest"]'
      python-version: '["3.8", "3.12"]'

  publish-test:
    name: Publish to test.pypi
    uses: ./.github/workflows/_publish.yaml
    with:
      pypi: test.pypi
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
