name: Test and Build

on:
  push:
    branches: [main, dev]
  workflow_dispatch:
  workflow_call:
    inputs:
      os:
        description: 'Operating system'
        default: '["ubuntu-latest"]'
        type: string
        required: false
      python-version:
        description: 'Python version'
        default: '["3.9", "3.12"]'
        type: string
        required: false

jobs:
  ci-test:
    name: CI tests
    uses: glenn20/python-ci/.github/workflows/_ci_tests.yaml@main
    with:
      os: ${{ inputs.os }}
      python-version: ${{ inputs.python-version }}
    permissions:
      id-token: none

  publish-test:
    name: Publish to test.pypi
    runs-on: ubuntu-latest
    steps:
      - uses: glenn20/python-ci/publish@main
        with: { pypi: test.pypi }
    environment:
      name: publish-test.pypi
      url: https://test.pypi.org/p/glenn20-python-ci
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing!
